[31mFATA[0m[2024-03-15T21:02:57+05:00]main.go:39 main.main() failed to initialize db: dial tcp [::1]:5436: connect: connection refused 
[31mERRO[0m[2024-03-15T21:05:47+05:00]reponse.go:14 todoApp/internal/handler.newErrorResponse() invalid username                             
[31mERRO[0m[2024-03-15T21:08:38+05:00]auth.go:46 todoApp/internal/handler.(*Handler).signIn() invalid username                             
[31mERRO[0m[2024-03-15T21:08:54+05:00]auth.go:46 todoApp/internal/handler.(*Handler).signIn() invalid password                             
[31mERRO[0m[2024-03-15T22:19:23+05:00]auth.go:40 todoApp/internal/handler.(*Handler).signIn() invalid password                             
[31mERRO[0m[2024-03-15T22:21:57+05:00]auth.go:40 todoApp/internal/handler.(*Handler).signIn() crypto/bcrypt: hashedPassword is not the hash of the given password 
[31mERRO[0m[2024-03-15T22:22:24+05:00]auth.go:40 todoApp/internal/handler.(*Handler).signIn() sql: no rows in result set                   
[31mERRO[0m[2024-03-15T23:04:15+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:04:15+05:00]middleware.go:27 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:04:21+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:04:21+05:00]middleware.go:27 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:04:26+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:04:26+05:00]middleware.go:27 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:04:27+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:04:27+05:00]middleware.go:27 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:04:27+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:04:27+05:00]middleware.go:27 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:04:57+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:04:57+05:00]middleware.go:27 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:06:16+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:06:48+05:00]middleware.go:28 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:06:56+05:00]auth.go:40 todoApp/internal/handler.(*Handler).signIn() sql: no rows in result set                   
[31mERRO[0m[2024-03-15T23:07:03+05:00]auth.go:20 todoApp/internal/handler.(*Handler).signUp() pq: duplicate key value violates unique constraint "users_username_key" 
[31mERRO[0m[2024-03-15T23:07:13+05:00]auth.go:40 todoApp/internal/handler.(*Handler).signIn() crypto/bcrypt: hashedPassword is not the hash of the given password 
[31mERRO[0m[2024-03-15T23:07:35+05:00]middleware.go:28 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:07:36+05:00]middleware.go:28 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:07:53+05:00]auth.go:20 todoApp/internal/handler.(*Handler).signUp() pq: duplicate key value violates unique constraint "users_username_key" 
[31mERRO[0m[2024-03-15T23:08:27+05:00]middleware.go:28 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-15T23:09:08+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:09:09+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:09:13+05:00]middleware.go:35 todoApp/internal/handler.(*Handler).userIdentify() token is malformed: token contains an invalid number of segments 
[31mERRO[0m[2024-03-15T23:12:12+05:00]middleware.go:35 todoApp/internal/handler.(*Handler).userIdentify() token is malformed: could not JSON decode header: invalid character 'Ãƒ' looking for beginning of value 
[31mERRO[0m[2024-03-15T23:12:31+05:00]middleware.go:21 todoApp/internal/handler.(*Handler).userIdentify() empty auth header                            
[31mERRO[0m[2024-03-15T23:12:38+05:00]middleware.go:28 todoApp/internal/handler.(*Handler).userIdentify() invalid auth header                          
[31mERRO[0m[2024-03-16T02:50:57+05:00]list.go:29 todoApp/internal/handler.(*Handler).createList() pq: column "title" of relation "list_items" does not exist 
[31mERRO[0m[2024-03-16T02:51:50+05:00]list.go:29 todoApp/internal/handler.(*Handler).createList() pq: column "title" of relation "list_items" does not exist 
[31mERRO[0m[2024-03-16T02:53:24+05:00]list.go:29 todoApp/internal/handler.(*Handler).createList() sql: no rows in result set                   
[31mERRO[0m[2024-03-16T02:55:55+05:00]list.go:29 todoApp/internal/handler.(*Handler).createList() sql: no rows in result set                   
[31mERRO[0m[2024-03-16T02:58:11+05:00]list.go:29 todoApp/internal/handler.(*Handler).createList() pq: insert or update on table "users_lists" violates foreign key constraint "users_lists_list_id_fkey" 
